PARTIES = [
    {"id": "psoe", "name": "PSOE", "scope": "nacional", "photo": "psoe", "data_status": "provisional"},
    {"id": "pp", "name": "Partido Popular", "scope": "nacional", "photo": "pp", "data_status": "provisional"},
    {"id": "vox", "name": "Vox", "scope": "nacional", "photo": "vox", "data_status": "provisional"},
    {"id": "sumar", "name": "Sumar", "scope": "nacional", "photo": "sumar", "data_status": "provisional"},
    {"id": "podemos", "name": "Podemos", "scope": "nacional", "photo": "podemos", "data_status": "provisional"},
    {"id": "pcte", "name": "PCTE", "scope": "nacional", "photo": "pcte", "data_status": "provisional"},
    {"id": "frente_obrero", "name": "Frente Obrero", "scope": "nacional", "photo": None, "data_status": "provisional"},
    {"id": "pacma", "name": "PACMA", "scope": "nacional", "photo": None, "data_status": "provisional"},
    {"id": "erc", "name": "ERC", "scope": "catalunya", "photo": "erc", "data_status": "provisional"},
    {"id": "junts", "name": "Junts", "scope": "catalunya", "photo": "junts", "data_status": "provisional"},
    {"id": "cup", "name": "CUP", "scope": "catalunya", "photo": None, "data_status": "provisional"},
    {"id": "bildu", "name": "EH Bildu", "scope": "euskadi_navarra", "photo": "eh bildu", "data_status": "provisional"},
    {"id": "pnv", "name": "PNV", "scope": "euskadi", "photo": "pnv", "data_status": "provisional"},
    {"id": "bng", "name": "BNG", "scope": "galicia", "photo": None, "data_status": "provisional"},
    {"id": "coalicion_canaria", "name": "Coalición Canaria", "scope": "canarias", "photo": None, "data_status": "provisional"},
    {"id": "nueva_canarias", "name": "Nueva Canarias", "scope": "canarias", "photo": None, "data_status": "provisional"},
    {"id": "upn", "name": "UPN", "scope": "navarra", "photo": None, "data_status": "provisional"},
    {"id": "teruel_existe", "name": "Teruel Existe", "scope": "aragon", "photo": None, "data_status": "provisional"},
    {"id": "soria_ya", "name": "Soria ¡Ya!", "scope": "castilla_y_leon", "photo": None, "data_status": "provisional"},
]

# Escala provisional de -2 a +2. Sustituir por posiciones extraídas,
# citadas y revisadas a partir de programas y votaciones oficiales.
PARTY_POSITIONS = {
    "psoe": [1, -1, 2, 1, 1, 2, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1],
    "pp": [-1, 1, 0, -1, -1, 0, 1, -1, -1, 1, -1, 1, 0, -1, -1, -1],
    "vox": [-1, 1, -1, -1, -1, -1, 2, -1, -1, 2, -1, 1, 1, -1, -1, -1],
    "sumar": [2, -1, 2, 2, 1, 2, -1, 1, 2, -1, 1, -1, -1, 2, 2, 2],
    "podemos": [2, -1, 2, 2, 2, 2, -1, 1, 2, -1, 1, -1, -1, 2, 2, 2],
    "pcte": [2, 1, 2, 2, 2, 1, -1, 1, 1, -1, 0, 0, 1, 1, 2, 2],
    "frente_obrero": [1, 0, 1, 0, 1, -1, 2, -1, -1, 2, -1, 1, 1, -1, -1, -1],
    "pacma": [1, -1, 1, 1, 1, 2, -1, 2, 2, 0, 0, 0, -1, 1, 2, 1],
    "erc": [1, 0, 1, 1, 1, 2, -1, 1, 1, -1, 2, -1, 0, 2, 2, 1],
    "junts": [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2, -1, 0, 2, 1, 0],
    "cup": [2, -1, 2, 2, 2, 2, -1, 1, 2, -1, 2, -1, 1, 2, 2, 2],
    "bildu": [2, -1, 2, 1, 2, 2, -1, 1, 1, -1, 2, -1, 0, 2, 2, 1],
    "pnv": [0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 2, -1, -1, 2, 1, 0],
    "bng": [2, -1, 2, 1, 2, 2, -1, 1, 1, -1, 2, -1, 0, 2, 2, 2],
    "coalicion_canaria": [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, -1, 1, 0, 0],
    "nueva_canarias": [1, -1, 2, 1, 1, 1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1],
    "upn": [-1, 1, 0, -1, -1, 0, 1, -1, -1, 1, -1, 1, 0, -1, -1, -1],
    "teruel_existe": [0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0],
    "soria_ya": [0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
}
