POLITIC_QUESTIONS = {
    'q1': "El Estado debería redistribuir la riqueza de los más ricos a los más pobres",
    'q2': "El mercado laboral debería ser flexible, permitiendo despidos y contrataciones libres con mínima regulación estatal",
    'q3': "La sanidad debería ser completamente pública y gratuita para todos, incluidos los inmigrantes",
    'q4': "El impuesto de sucesiones debe eliminarse para evitar la doble imposición a las familias",
    'q5': "El Estado debería intervenir fuertemente en la economía para garantizar igualdad de oportunidades",
    'q6': "El país debería permitir la entrada libre de inmigrantes y facilitar su integración en la sociedad",
    'q7': "Las pensiones deberían ser privadas y depender de los ahorros individuales, no de un sistema público",
    'q8': "España debe implementar restricciones más severas al uso de coches de combustión, promoviendo los coches eléctricos, a pesar de las implicaciones económicas y medioambientales de su producción, el coste elevado para los ciudadanos y el impacto en la industria automovilística tradicional",
    'q9': "Las regiones que lo deseen deberían poder celebrar referéndums para decidir su independencia",
    'q10': "Sindicatos, partidos políticos y medios de comunicación deben recibir subvenciones públicas para su funcionamiento",
    'q11': "Hay una correlación entre inmigración y delincuencia en algunos colectivos culturales",
    'q12': "Es suficiente con que una persona se identifique como mujer para serlo, independientemente de su sexo biológico",
    'q13': "Todos los ciudadanos deberían recibir una Renta Básica Universal garantizada por el Estado",
    'q14': "Se debería priorizar la natalidad de los ciudadanos nacionales sobre la de inmigrantes para preservar la identidad cultural",
    'q15': "El Estado debería priorizar el uso de energías renovables, incluso si esto implica un mayor coste económico o perjuicios medioambientales, como la pérdida de tierras de cultivo o biodiversidad",
    'q16': "Dado el elevado nivel de deuda pública en España, se deberían seguir priorizando ayudas públicas y el mantenimiento del estado de bienestar, aunque ello implique un aumento de impuestos como el IVA y el IRPF",
}
