POLITIC_QUESTIONS = [
    {"id": "taxes", "axis": "economy", "section": "Economía", "text": "El Estado debería cobrar más impuestos a las rentas altas para financiar servicios públicos.", "direction": 1},
    {"id": "market", "axis": "economy", "section": "Economía", "text": "Reducir impuestos y regulación debería ser prioritario para facilitar la actividad de empresas y autónomos.", "direction": -1},
    {"id": "services", "axis": "economy", "section": "Servicios públicos", "text": "Sanidad, educación y dependencia deberían ser principalmente públicas, aunque requieran más impuestos.", "direction": 1},
    {"id": "housing", "axis": "economy", "section": "Vivienda", "text": "El Estado debería regular los alquileres en las zonas donde la vivienda sea inasequible.", "direction": 1},
    {"id": "pensions", "axis": "economy", "section": "Economía", "text": "Las pensiones públicas deberían protegerse aunque haya que aumentar ingresos o cotizaciones.", "direction": 1},
    {"id": "rights", "axis": "social", "section": "Derechos y libertades", "text": "Las leyes deberían ampliar la libertad individual aunque contradigan costumbres tradicionales.", "direction": 1},
    {"id": "security", "axis": "social", "section": "Seguridad", "text": "Para reducir la delincuencia deberían priorizarse penas más duras y más presencia policial.", "direction": -1},
    {"id": "migration", "axis": "social", "section": "Inmigración", "text": "España debería facilitar la inmigración legal cuando exista un plan real de integración.", "direction": 1},
    {"id": "climate", "axis": "social", "section": "Energía y clima", "text": "La transición ecológica debería acelerarse aunque algunas medidas encarezcan el consumo a corto plazo.", "direction": 1},
    {"id": "tradition", "axis": "social", "section": "Valores", "text": "La familia, la tradición y la autoridad deberían tener más peso en las políticas públicas.", "direction": -1},
    {"id": "territory", "axis": "identity", "section": "Modelo territorial", "text": "Las comunidades con una identidad nacional propia deberían poder decidir más sobre su futuro político.", "direction": 1},
    {"id": "centralization", "axis": "identity", "section": "Modelo territorial", "text": "España debería reforzar unas instituciones comunes y reducir la fragmentación territorial.", "direction": -1},
    {"id": "europe", "axis": "identity", "section": "Europa", "text": "La Unión Europea debería tener más competencias compartidas aunque España pierda parte de su margen de decisión.", "direction": -1},
    {"id": "culture", "axis": "identity", "section": "Identidad y cultura", "text": "Las lenguas y culturas propias de cada territorio deberían tener más reconocimiento institucional.", "direction": 1},
    {"id": "democracy", "axis": "identity", "section": "Democracia", "text": "España debería reformar sus instituciones para dar más peso a la participación directa y a las listas abiertas.", "direction": 1},
    {"id": "monarchy", "axis": "identity", "section": "Instituciones", "text": "La jefatura del Estado debería elegirse mediante votación ciudadana.", "direction": 1},
]
